### ISSUE TITLE
Error at the chapter 7 - word2vec_cbow.py

### ISSUE THREAD

**Issue by sigmoidx** [PacktPublishing/TensorFlow-Machine-Learning-Cookbook#1]
Hello?

I have been reading this book and there is some error I do not know how to solve in the chapter 7.
In word2vec_cbow.py and text_helpers.py,

**I made some corrections first.**

**from:**
loss = tf.reduce_mean(tf.nn.nce_loss(nce_weights, nce_biases, embed, y_target,
                                     num_sampled, vocabulary_size))
**to:**
loss = tf.reduce_mean(tf.nn.nce_loss(weights=nce_weights, biases=nce_biases, labels=y_target, 
                                     inputs=embed, num_sampled=num_sampled, num_classes=vocabulary_size)) 

**from:** 
 with open(pos_file, 'r') as temp_pos_file:
            for row in temp_pos_file:
                pos_data.append(row)
        neg_data = []
        with open(neg_file, 'r') as temp_neg_file:
            for row in temp_neg_file:
                neg_data.append(row)

**to:**
 with open(pos_file, 'r', encoding='ISO-8859-1', errors='ignore') as temp_pos_file:
            for row in temp_pos_file:
                pos_data.append(row)
        neg_data = []
        with open(neg_file, 'r', encoding='ISO-8859-1', errors='ignore') as temp_neg_file:
            for row in temp_neg_file:
                neg_data.append(row)

**And this error is popping out and I don't know how to solve this:**

Traceback (most recent call last):
  File "word2vec_cbow.py", line 123, in <module>
    batch_inputs, batch_labels = text_helpers.generate_batch_data(text_data, batch_size, window_size, method='cbow')
  File "/home/tester/libs/cookbook/Chapter 7/text_helpers.py", line 97, in generate_batch_data
    batch, labels = [list(x) for x in zip(*batch_and_labels)]
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Keramatfar** [comment]
Hi,
The problem is in this line:
batch_and_labels = [(x,y) for x,y in batch_and_labels if len(x)==2*window_size]
if the length of comment be smaller than 7, this line return an empty list, that cause error in this line:
batch, labels = [list(x) for x in zip(*batch_and_labels)].
To avoid this i set the minimum length at these lines:
target = [target[ix] for ix, x in enumerate(texts) if len(x.split()) > 6]
texts = [x for x in texts if len(x.split()) > 6].

**Comment by MurtazaTinwala** [comment]
Hi @majomuchi123 

TensorFlow Machine Learning Cookbook - Second Edition is out now. 
Please have a look for all the updated content and codes in the new book on these links: 

Packt website - https://www.packtpub.com/big-data-and-business-intelligence/tensorflow-machine-learning-cookbook-second-edition

Amazon - https://www.amazon.com/dp/1789131685
