### ISSUE TITLE
Some question about TensorFlow-Machine-Learning-Cookbook/Chapter 05/nearest_neighbor.py

### ISSUE THREAD

**Issue by vocaliodmiku** [PacktPublishing/TensorFlow-Machine-Learning-Cookbook#3]
line73:``distance = tf.reduce_sum(tf.abs(tf.sub(x_data_train, tf.expand_dims(x_data_test,1))), reduction_indices=2)``
 I dont understand this line. i think L1 norm is :
`distance = tf.reduce_sum(tf.abs(tf.sub(x_data_train, x_data_test))), reduction_indices=2`
your code is `tf.expand_dims(x_data_test,1)`instead of  `x_data_test`,can you explain the ops that  subtract
2D-tensor from 3D-tensor.thanks you very much

**Comment by MurtazaTinwala** [comment]
Hi @majomuchi123 

TensorFlow Machine Learning Cookbook - Second Edition is out now. 
Please have a look for all the updated content and codes in the new book on these links: 

Packt website - https://www.packtpub.com/big-data-and-business-intelligence/tensorflow-machine-learning-cookbook-second-edition

Amazon - https://www.amazon.com/dp/1789131685
