### ISSUE TITLE
Question about SVM with kernels.

### ISSUE THREAD

**Issue by KLiFF2606** [PacktPublishing/TensorFlow-Machine-Learning-Cookbook#8]
Hi,

I have a question about this line from the notebook named "04_svm_kernels":
`sq_dists = tf.add(tf.subtract(dist, tf.multiply(2., tf.matmul(x_data, tf.transpose(x_data)))), tf.transpose(dist))`

It looks too complicated than the distance required by the Gaussian Kernel.

An other question is about the prediction tensor: it accepts a batch of data as a training samples. Is not the SVM supposed to identify the Support Vector and thereby learn the relevant data points in order to make a prediction? These data points aren't they to be kept by the model from the training data set?

Thank you in advance.

**Comment by MurtazaTinwala** [comment]
Hi @majomuchi123 

TensorFlow Machine Learning Cookbook - Second Edition is out now. 
Please have a look for all the updated content and codes in the new book on these links: 

Packt website - https://www.packtpub.com/big-data-and-business-intelligence/tensorflow-machine-learning-cookbook-second-edition

Amazon - https://www.amazon.com/dp/1789131685
