### ISSUE TITLE
tf.concat not working

### ISSUE THREAD

**Issue by dipta007** [PacktPublishing/TensorFlow-Machine-Learning-Cookbook#9]
On these lines, I have to send the axis parameter later, the order is different now on tensorflow=1.12.0
I think it would be better to use keyword arguments than positional arguments in these cases

https://github.com/PacktPublishing/TensorFlow-Machine-Learning-Cookbook/blob/47c240d7fb9842f36ef2a51514dfce62bb973b6a/Chapter%2007/doc2vec.py#L112

https://github.com/PacktPublishing/TensorFlow-Machine-Learning-Cookbook/blob/47c240d7fb9842f36ef2a51514dfce62bb973b6a/Chapter%2007/doc2vec.py#L213

**Comment by MurtazaTinwala** [comment]
Hi @majomuchi123 

TensorFlow Machine Learning Cookbook - Second Edition is out now. 
Please have a look for all the updated content and codes in the new book on these links: 

Packt website - https://www.packtpub.com/big-data-and-business-intelligence/tensorflow-machine-learning-cookbook-second-edition

Amazon - https://www.amazon.com/dp/1789131685

**Comment by elvin365** [comment]
@MurtazaTinwala, even in Second edition the examples code are still tensorflow v.1. Are there newer versions of examples using tensorflow 2?
